apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yoon-gitaly-pvc
  namespace: yoon-gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: yoon-gitaly-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yoon-minio-pvc
  namespace: yoon-gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: yoon-minio-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yoon-redis-pvc
  namespace: yoon-gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: yoon-redis-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yoon-postgresql-pvc
  namespace: yoon-gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: yoon-postgresql-pv
  storageClassName: hostpath

